# Generated by Django 4.1 on 2022-08-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='updates',
            name='img',
            field=models.ImageField(default=1234, upload_to='galleryy'),
            preserve_default=False,
        ),
    ]
